@Accommodations_API_HostAddress = https://localhost:7257


GET {{Accommodations_API_HostAddress}}/api/healthcheck

###

GET {{Accommodations_API_HostAddress}}/api/accommodations

###

GET {{Accommodations_API_HostAddress}}/api/accommodations/34e8a049-6b33-4f43-9dc9-08dc8d0eef6c

###

POST {{Accommodations_API_HostAddress}}/api/accommodations
Content-Type: application/json

{
  "name": "Sunny Villa",
  "description": "Spacious villa with a beautiful view.",
  "type": "Resort",
  "hasInstantBooking": false,
  "contactEmail": "contact@sunnyvilla.com",
  "contactNumber": "+987654321",
  "city": "Copenhagen",
  "street": "789 Beach Avenue",
  "postalCode": "2100"
}
